### ISSUE TITLE
rpca falls over with k=1 when retx=TRUE

### ISSUE THREAD

**Issue by wmacnair** [erichson/rSVD#3]
Hi

Running rpca with k=1 and retx=TRUE gets the following error:
```
# set up
library('rsvd')
data('iris')
log_iris 		= log( iris[ , 1:4] )
iris_species 	= iris[ , 5]
# Perform rPCA and compute only the first two PCs
iris_rpca 		= rpca(log_iris, k=1, retx=TRUE)
# Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
```

I think you've forgotten a `drop=FALSE` in line ~64 in _rpca.default_, so it should be:
```
rpcaObj$x <- sweep(out$u[, 1:k, drop=FALSE], MARGIN = 2, STATS = out$d[1:k], FUN = "*", check.margin = TRUE)
```
(this now works for me)

Cheers!
Will

**Comment by erichson** [comment]
@wmacnair this is amazing! Thank you for spotting and providing the solution. I should have cached this error, but it slipped through my tests.

I will update it later today. Please, let me know if you catch any other errors. 

Best,
Ben

**Comment by erichson** [comment]
@wmacnair  I updated the code regarding your suggestions. Seems to work now:

```
devtools::install_github("erichson/rsvd")
# set up
library('rsvd')
data('iris')
log_iris 		= log( iris[ , 1:4] )
iris_species 	= iris[ , 5]
# Perform rPCA and compute only the first two PCs
iris_rpca 		= rpca(log_iris, k=1, retx=TRUE)
```

Let me know if that works for you too.

Best,
Ben
