### ISSUE TITLE
NULL output from rsvd when nu=0 or nv=0

### ISSUE THREAD

**Issue by LTLA** [erichson/rSVD#6]
Currently, `rsvd` sets the output `$u` or `$v` to `NULL` when `nu=0` or `nv=0`, respectively. 

Is this really necessary? It complicates downstream processing for client packages, which now have to check whether `$u` is `NULL` before attempting to perform an operation on it. 

You might say that one shouldn't be doing anything on `$u` if `nu=0`, and that would be mostly correct - I'm not using that output for anything meaningful. But I do have to do some sanity checks, coercions and renamings, and it's a bother to have to check for `NULL` every time.

It seems easier for the both of us to simply require `nu=0` result in an empty matrix with no columns. This means that you don't have to have the special code to set it to `NULL`, and also the output is consistent with the documentation in `?rsvd` with no surprising behaviours; while I can be secure in knowing that I get a matrix with zero SVs if I asked for it, without worrying about a sudden `NULL`.

**Comment by erichson** [comment]
@LTLA this is a subtle issue. Returning zero vectors / matrices for ```$u``` and ```$v``` is not correct. That is, because the zero component does not correspond to a singular value that has magnitude larger than zero, i.e., the following statement is not correct 
```
t($u) %*% A %*% $v = $d
```
when ```$u = matrix(0, ...)``` and ```$v = matrix(0, ...)``` for ```$d_1>...>$d_k > 0```.

It seems that the base svd function is not returning either ```$u``` or ```$v``` if ```nu=nv=0```.

Best
B

**Comment by erichson** [comment]
@LTLA, okay one option is, as you suggested, to use ```matrix(, nrow = m, ncol = k)```. This creates a vector / matrix that has ```NA``` as entries. Do you think this would be more convenient?

**Comment by LTLA** [comment]
> It seems that the base svd function is not returning either `$u` or `$v` if `nu=nv=0`.

Hm, you're right. Made me wonder why my _BiocSingular_ package was working with `svd` but not `rsvd`... and then I realized I had written a `safe_svd` wrapper around the former to replace the `NULL`s. Oops.

> when `$u = matrix(0, ...)` and `$v = matrix(0, ...)` for `$d_1>...>$d_k > 0`.

Just to be clear, I was suggesting to have `$u = matrix(..., ncol=0)`. So "empty" refers to "no column vectors at all" rather than values of zero. This would avoid suggesting any incorrect relationship about the relationship between `$u`, `$v` and `$d`; an empty matrix should serve the same purpose as a `NULL` in terms of indicating that there are no singular vectors extracted, but in a more friendly way to client code. (Specifically, code that was working with `nu=1` will easily work with `nu=0` if it weren't for the `NULL`.)

I mean, if you want to keep consistency with `base::svd()`'s output, I'd understand. But it seems like returning an empty matrix would save both of us some work. And besides, I would say that `base::svd()`'s default behaviour with `nu=0` is itself pretty annoying (and undocumented, AFAICT).

**Comment by LTLA** [comment]
Actually, this behavior does manifest in a related bug:

https://github.com/erichson/rSVD/blob/f30a5afd448d89ab19823d0096cb5ef966b149b7/R/rsvd.R#L233-L234

If `flipped=TRUE`, `nu` and `nv` have been swapped at line 158. But they haven't been unswapped by the time they get to lines 233-234, meaning that the wrong values are set to `NULL`.

```r
X <- matrix(runif(10000), 50, 1000)

library(rsvd)
out <- rsvd(X, k=25, nu=25, nv=0)
str(out) # No left singular vectors!
## List of 1
##  $ d: num [1:25] 112.5 13.1 12.8 12.5 12 ...
##  - attr(*, "class")= chr "rsvd"
```

The simple fix would be to move the `NULL` setting lines above line 224.

<details>
<summary>Session info</summary>

```
R version 3.6.0 Patched (2019-05-02 r76458)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /home/luna/Software/R/R-3-6-branch-dev/lib/libRblas.so
LAPACK: /home/luna/Software/R/R-3-6-branch-dev/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsvd_1.0.1    Matrix_1.2-17

loaded via a namespace (and not attached):
[1] compiler_3.6.0  grid_3.6.0      lattice_0.20-38
```
</details>

**Comment by erichson** [comment]
@LTLA that is great! Thanks for spotting this bug. 

Do you have time to merge your solution to the package? Otherwise, I can do it the week after next.

Best
B

**Comment by LTLA** [comment]
Would you be able to push it up to CRAN soon-ish? This bug is currently blocking some of my collaborators' projects, and it's just easier for me to tell them to get the latest CRAN version. (Not least because the version number here is below that on CRAN, so even if they did install from here, they'd end up reverting to the buggy version as soon as they update their packages!)

**Comment by erichson** [comment]
Yes, let me try to push a new version later tonight or tomorrow. There are a couple of other small issues that I need to fix... And I will also push all other changes to github so that versions match again.

Best,
B

**Comment by erichson** [comment]
@LTLA new version is pushed to CRAN. Will probably take a day or two...
