### ISSUE TITLE
Wrong pca$sdev for the first pca component (after calling rsvd::rpca)

### ISSUE THREAD

**Issue by dsvolkov** [erichson/rSVD#8]
Hi! Thank you for nice package. 

I'm running 
```
pca <- rsvd::rpca(data, 10) 
sdev <- apply(pca$x, 2, sd)
```

and then comparing sdev with pca$sdev. It's basically the same except the first principal component. Here is the output for my sample data:

```
> sdev
 [1] 3.718906 3.480278 2.946602 2.451098 1.920354 1.913088 1.768413 1.758458 1.722685 1.650044
> pca$sdev
 [1] 12.668942  3.483281  2.964610  2.452116  1.935481  1.919646  1.771491  1.763022  1.724073  1.650757
```

**Comment by erichson** [comment]
Hello @dsvolkov,

Happy to hear that you like my package. I am a bit puzzled by your results, and I cannot reproduce them.  Here is what I tried (and I get correct results).

```
some_data <- function(n, p, k) {
  set.seed(42)
  a = matrix(runif(n*k), n, k)
  b = matrix(runif(p*k), k, p)
  X = a %*% b
  return(X)
}

data <- some_data(50, 50, 10)

pca <- rsvd::rpca(data, 10) 
sdev <- apply(pca$x, 2, sd)

print(pca$sdev)
print(sdev)
```


And here the output:

```
[1] 5.9475026 1.7790400 1.6465112 1.4765830 1.3336371 1.2647160 1.0712669 0.9752757 0.8242359 0.6439709
 
[1] 5.9475026 1.7790400 1.6465112 1.4765830 1.3336371 1.2647160 1.0712669 0.9752757 0.8242359 0.6439709
```

Can you share your data with me?

Best,
Ben

**Comment by dsvolkov** [comment]
Oh, I forgot to mention the important detail, the data is sparse - Matrix::sparseMatrix. Could you try it? If not, I suppose I can send a sample of data to you.

**Comment by dsvolkov** [comment]
Oh, It seems I forgot to mention a significant detail, I'm using center = FALSE. So

```
some_data <- function(n, p, k) {
  set.seed(42)
  a = matrix(runif(n*k), n, k)
  b = matrix(runif(p*k), k, p)
  X = a %*% b
  return(X)
}

data <- some_data(50, 50, 10)

pca <- rsvd::rpca(data, 10, center = FALSE) 
sdev <- apply(pca$x, 2, sd)

print(pca$sdev)
print(sdev)
```

gives

```
> print(pca$sdev)
 [1] 7.0303104 0.3533804 0.3365583 0.2932263 0.2615945 0.2508934 0.2056525 0.1887109 0.1601924 0.1251368
> print(sdev)
 [1] 1.1348023 0.3533657 0.3365575 0.2932104 0.2615907 0.2508848 0.2056427 0.1887057 0.1600791 0.1250817
```

**Comment by erichson** [comment]
@dsvolkov I am somewhat confused. Why do you expect in this case (i.e., center==False) that pca$sdev and  apply(pca$x, 2, sd)  would yield the same results? 

Try, the prcomp function:
```
pca <- prcomp(data, rank.=10, center = FALSE) 
sdev <- apply(pca$x, 2, sd)

print(pca$sdev)
print(sdev)
```
This is not a bug.  

Best,
Ben

**Comment by dsvolkov** [comment]
Yeah, you are right, it's my fault
